apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com'
    targetRevision: HEAD
    path: apps/payment-service
  destination:
    server: 'https://default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
