apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sConstraintNoPrivilegedContainers
metadata:
  name: security-policy-block-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - production
